### ISSUE TITLE
continuous integration with CircleCI

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo#10]
### continuous integration with CircleCI #10

- [x] sign up for free CircleCI account through GitHub
- [x] cebcar Settings: GitHub Apps: CircleCI: allow CircleCI repository access to cebcar/Tuxedo

Learn:
- [ ] [CircleCI Basics](https://circleci.com/docs/2.0/basics/)

Tutorials to start real jobs:
- [ ] [Hello World On macOS](https://circleci.com/docs/2.0/hello-world/)
- [ ] [Automate Your Static Site Deployment with CircleCI](https://circleci.com/blog/automate-your-static-site-deployment-with-circleci/)

Reference:
- [ ] CircleCI: [Using Shell Scripts](https://circleci.com/docs/2.0/using-shell-scripts/)
