### ISSUE TITLE
tool iTerm2

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo#13]
#### iTerm2
- [ ] iTerm_keys.html
- [ ] document tool/iTerm2  #41<br><br>

### > Installation
- [ ] prepare for clean iTerm2 installation and configuration<br><br>

  - [ ] uninstall existing iTerm2
    *tool was used to help recover some git commits; configuration not complete or documented*
  - apparently, just put in the trash and then empty the trash. <br><br>

- [ ] `brew cask install iTerm2`<br><br>

#### Fonts
Powerline Fonts are a group of patched fonts that contain special characters for use in status lines.
- [ ] install both of fonts:
  - [Meslo](https://github.com/powerline/fonts/blob/master/Meslo%20Slashed/Meslo%20LG%20M%20Regular%20for%20Powerline.ttf) (select view raw)
    - standard Recommendation; based on Menlo, which have been using
  - [Source Code Pro](https://github.com/powerline/fonts/blob/master/SourceCodePro/Source%20Code%20Pro%20for%20Powerline.otf)
    - apparently, some 14 point fonts are not perfectly aligned, and this one is an alternative if that is a problem<br><br>

- [ ] configure as in iTerm2.md<br><br>

#### iTerm2 Shell Integration
- [ ] document iTerm2 Shell Integration
[iTerm2 Shell Integration](https://iterm2.com/documentation-shell-integration.html)

#### iTerm2 References
[Clovis Terminal Configuration](https://medium.com/@Clovis_app/configuration-of-a-beautiful-efficient-terminal-and-prompt-on-osx-in-7-minutes-827c29391961)
[iTerm2 Cheatsheet](https://kapeli.com/cheat_sheets/iTerm2.docset/Contents/Resources/Documents/index)<br/><br/>
