### ISSUE TITLE
Establish Dev Workflows

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo#21]
## > Implementation <

- [ ] Task Branch Workflow
  - [ ] modified from Feature Branch Workflow
  - [ ] add 'git rebase -i main'
  - [ ] update with marked changes
  - [ ] add Pull Request<br/><br/>

- [ ] Overview document Development Workflows <br/><br/>

- [ ] Release Workflow <br/><br/>

- [ ] Pull Request, including for Open Source <br/><br/>
