### ISSUE TITLE
Recover Legacy Issues

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo#26]
##### cebcar
- [ ] incorporate issues as indicated
  - [ ] start-devops <br><br>

- [ ] check issues
  - [ ] first-tuxedo
  - [ ] start-devops
  - [ ] DevOps_docs <br><br>

##### carolclark
- [ ]  recent issues
  - [ ] Accessor
  - [ ] DevSupport
  - [ ] Punkin <br><br>

- [ ] check issues
  - [ ] DevOps-no-org <br><br>
