### ISSUE TITLE
establish new Tool file format

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo#29]
## Tool Profile
- Tool files include some standard information about the tool's version, licence, source, documentation, ...
- standard information included in the Tools file header includes  Configuration information, which can get long
- Alternatives Considered is also being added; could also be long, moving the main "Using ..." section even farther down

- so: change the header section at the top to a Profile section at the end

## > Tentative Format <
    ```markdown
      # ${NAME}
      [${NAME} Profile](#${NAME}-profile)
      $INDENT$*$BLURB$*<br/>
      ## Tool ${NAME}
      
      $END$<br/>
      
      ## *${NAME} Profile*
      $INDENT$$TOOLTYPE$ @ $LOCATION$<br/>$INDENT%*$BLURB$*<br/>
      
      **Version**: $VERSION$<br/>
      **Source**: $SOURCE$<br/>
      **Obtained**: $METHOD$; $DATE_PRICE$<br/>
      **License**: $LICENSE$<br/>
      **Critical Data**: $CRITICALDATA$<br/>
      **Installation**: $INSTALLATION$<br/>
      **Documentation**: $DOCUMENTATION$<br/>
      
      ### ${NAME} Configuration
      ### ${NAME} Automation
      ### ${NAME} Shortcuts
      ### ${NAME} Alternatives Considered 
    ```
## >> Implementation <<

- [ ] ***standardize header format  for 'tools/' documents cebcar/Tuxedo17***
standardize header format  for 'tools/' documents cebcar/Tuxedo#17

- [ ] standardize header format  for 'tools/' documents
  - add IntelliJ template 'c/tool' for Tool file with profile
  - changes:
    - get basic profile format from file GitHub.md
    - move current profile information to end of file
    - add Alternatives Considered
    - change "Shortcuts" to "Keymap"<br/><br/>
  - document
    - entity 'tool', with its standard file format and adoption process
      - can use generic filename (eg, Drawing Tool) during evaluation; change to name of tool selected (eg. Figma)
    - use IntelliJ template to create 'tools/' issues 

### ***add link from document heading to "&lt;toolname&gt; Profile"***
- [ ] add link from document heading to "&lt;toolname&gt; Profile"
  - right-aligned, near top heading
- [ ] update existing documents to match

### ***javascript to repeat tool blurb***
- [ ] javascript to repeat tool blurb
  - see [Embed javascript in markdown](https://stackoverflow.com/questions/2754391/embed-javascript-in-markdown)
