### ISSUE TITLE
revise Feature Branch Workflow

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo#3]
### revise Feature Branch Workflow #3

- [ ] update Feature single branch WF #20
- [ ] Feature Branch WF: multiple branches #21
- [ ] Atom Linter #46
- [ ] Feature Branch WF: pull requests #22
