### ISSUE TITLE
Establish Dev Workflows

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo#32]
### Establish Dev Workflows cebcar/Tuxedo#32

- [ ] Establish Initial Workflows
  - [ ] new Task Branch Workflow cebcar/Tuxedo-ij#26
  - [ ] overview document DevelopmentWorkflows
  - [ ] Release Workflow
  - [ ] Pull Request Workflow for Open Source
  - [ ] Deprecation workflow
    - related to Versioning system
