### ISSUE TITLE
recover Tuxedo legacy

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo#36]
### recover Tuxedo legacy cebcar/Tuxedo#36

*recovery: issues, content, false starts related to move to project Tuxedo*
 
#### cebcar
- Tuxedo *current*
- Penguins *current, for learning activities*
- ij-config *current IntelliJ Settings Repository* <br><br>

#### > Implementation
- [ ] Recover Legacy Code cebcar/Tuxedo#38

- [ ] Recover Legacy Issues cebcar/Tuxedo#26

- [ ] cleanup/remove old GitHub Repos cebcar/Tuxedo-ij#113
