### ISSUE TITLE
PDF from GitHub issue

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo#48]
--test<style>
.green {
    color: green;
    font-weight:700;
    font-size: 30px;
}
</style>

<div class="green">
    Markdown css styles
</div>

- the above leading styles work when converted to html

#### Initial process Process for MMC meeting Thurs 24 Feb
- [x] new issue 'forMMC-02.24.2022': start with content from for Peregrine #53 forAaron.02.15
- [x] remove/update narrative email content
- [ ] convert content of Markdown issue to HTML; save as PDF/html/forMMC-02.24.2022.html
- [ ] Atom: add package atom-html-preview
  - add package; document at "tool Atom" #2
Styling
  -  add css to:
    - [ ] make images smaller
    - [ ] (if time): add css element for text paragraph with image to the right<br><br>

- [ ] use html to pdf converter to create PDF

- [ ] update as indicated for new content in original issue
  - update issue
  - copy content
  - convert to html; save as PDF/conversion/forMMC-02.24.2022.html
  - convert to PDF; save at PDF/agendas/forMMC-02.24.2022.pdf<br><br>

- [ ] email to list
