### ISSUE TITLE
git configuration

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo#5]
### git configuration #5

*correct location for global files is ~/; any files at / would be 'system' files*

see ([How to Setup Git, GitHub, and Atom](https://packitforwarding.com/index.php/2019/06/26/how-to-setup-git-github-and-atom/))

- [x] cebcar/Tuxedo #6 global git config<br><br>
   
- [x] try Atom as git core.editor
`git config --global core.editor "atom --wait"`<br><br>

- [ ] document configuration plan @ tools/git 
  - include:
    - our global (at ~/) git configuration is sufficient to start simple projects
    - project root contains any project-specific content
> Note:
   for git attributes with Boolean values,
  &lt;attribute&gt; means use that attribute; -&lt;attribute&gt; means **omit** that attribute

##### > expect remaining items will be separate issues
- [ ] set up document headings with Keyword Expansion; see Git Book: [8.2 Customizing Git - Git Attributes](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes): Keyword Expansion
*add at least commit date* <br><br>

- [ ] script git configuration
  - scripts can be committed to repo without complications, and can put files where they need to be
  - gitignore.io can be scripted via `gi`
  - include comments in the scripts <br><br>

- [ ] handle GitHub Large File Storage #9; [Installing Git Large File Storage](https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage) 
sample section from config file:
```shell
[filter "lfs"]
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
```

- [ ] set up diff for binary files; see Git Book: [8.2 Customizing Git - Git Attributes](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes): Diffing Binary Files <br><br>

#### Later
Git: [Signing Your Work](https://www.git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work#_signing)
