### ISSUE TITLE
Initial Website

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo#53]
### > Before Builds Implemented <
- [x] print keymaps from IDE
- [ ] document printing HTML documents, including keymaps
  - Keymaps are in HTML.
  - From any HTML file, oF2 pops up a list of preview options.
  - Pick any external browser and to open, and print the file from there.

### > Deploy HTML Content <
  - [How to configure WebStorm to access your remote server via FTP](https://www.youtube.com/watch?v=2C6M1NlxD-8)

### > javascript <
*scripting language*

### > Node.js <
*javascript interpreter*
- [ ] Node.js setup cebcar/Tuxedo#54

### > Deploy Markdown Content <
- probably pandoc

### > React <
*UI component support with library*
- see Penguins: [React](https://github.com/cebcar/Penguins/issues/28)
##### [Creative Tim](https://www.creative-tim.com) (document)
- React Full Stack "Summer Stack" bundle purchased 02 Aug 2021
  - bundle price $199
  - Downloads
    - Creative Tim: [Downloads](https://www.creative-tim.com)
      - signin as Carol via GitHub; select My Purchases
      - links to: Documentation; GitHub project; Invitation; downloads for React, HTML, Designer

### > HTML include <
- [ ] HTML include cebcar/Tuxedo#55
