### ISSUE TITLE
Markdown Navigator Enhanced

### ISSUE THREAD

**Issue by carolclark** [cebcar/Tuxedo#8]
## Tool: Markdown Navigator Enhanced #8
  IntelliJ Plugin [Markdown Navigator 3.0](http://vladsch.com/product/markdown-navigator)
  *plugin for Markdown language support on IntelliJ IDEs*

#### Evaluate for possible adoption
- [x] ***Evaluate for possible adoption***
- many great features, including export to location as HTML (publish our TechDocs website)
- **very difficult to read for some features (eg. links) under darcula**
  - try for awhile to see if it's usable
    - 05/11/2021 figured out how to style  in Preferences with custom css, starting with Material theme
- accepted

#### add remaining css styles
- [ ] ***add remaining css styles***
  - add remaining css styles; tentatively Material based on [markdown-plus-plus](https://github.com/Edditoria/markdown-plus-plus)<br/><br/>

#### publish technical documentation
- [ ] ***publish technical documentation***
- publish technical documentation as a wiki; see [Documenting your projects on GitHub](https://guides.github.com/features/wikis/#creating-your-wiki)
- wiki does not support folders
  - use topic in filename (replace entities/RepoProject.md with entities-RepoProject.md (or entity-RepoProject.md)?)

## issue dependencies:
- enables: enhanced support for Mermaid and PlantUML<br/><br/>

## Documentation
- [ ] documentation content: update; copy to IntelliJ documentation file

# Markdown Navigator
## Markdown Navigator Tool

(content)

## *Markdown Navigator Profile*
Version: 3.0
License: Apache 2.0
Source: IntelliJ plugin purchased (<$10/yr) 04/28/2021
Documentation: [idea-multimarkdown](https://github.com/vsch/idea-multimarkdown/wiki)

### Markdown Navigator Configuration
- IntelliJ Prefs @ Languages &amp; FrameWorks : Markdown
  - Custom CSS: add Material-based settings; credit [markdown-plus-plus](https://github.com/Edditoria/markdown-plus-plus)
```css
body {
    background-color: #263238;
}

a:link {
    color: #F78C6C;
}
```    

### Markdown Navigator Alternatives Considered
- #### IntelliJ default Markdown support
  - rejected: Markdown Navigator has
    - many great features, including export to location as HTML (publish our TechDocs website)
    - minimal cost
